Create cartpole_dqn.py
rlcode/dqn pull request #1
Opened 2018-01-12 08:18 UTC by jcwleo

Create DQN agent

2018-01-12 08:41 UTC, keon requested changes
코멘트 몇개 달았습니다.
numpy와 pytorch를 오가는 경우가 많은데 이를 최소화 할 수 있으면 좋을 것 같습니다.

2018-01-12 08:41 UTC, keon commented on cartpole_dqn.py
> +        one_hot_action = Variable(torch.Tensor(one_hot_action))
```
one_hot_action = torch.FloatTensor(batch_size, action_size).zero_()
one_hot_action.scatter_(1, actions.data.unsqueeze(1), 1)
```

이렇게 하면 파이토치만 사용할 수 있습니다 (디멘션 맞는진 확인바람..)

2018-01-12 08:41 UTC, keon commented on cartpole_dqn.py
> +            return np.argmax(q_value[0])
argmax도 파이토치로 해결하면 더 쉽습니다
```
 q_value = self.model(state)
 _, action = torch.max(q_value, 1)
```
`max` 의 첫번째 리턴은 값, 두번째 리턴은 인덱스입니다.

2018-01-12 08:41 UTC, keon commented on cartpole_dqn.py
> +        one_hot_action = Variable(torch.Tensor(one_hot_action))
생각해보니 0으로 체운 (디멘션만 참고하여) 텐서를 만들때도
```
one_hot_action = torch.zeros_like(actions) 
```
하심 됩니다.

2018-01-12 08:41 UTC, keon commented on cartpole_dqn.py
> +        for i in range(self.batch_size):
뭔가 더 깔끔한 방법이 없을까요 ㅋㅋ 일단 패스

2018-01-12 08:41 UTC, keon commented on cartpole_dqn.py
> +def weights_init(model):
`DQN` 내부 함수로 만들어도 좋을것 같습니다

그리고 netG netD 코멘트 업뎃 필요한듯 ㅋㅋ

2018-01-12 08:42 UTC, dnddnjs commented on cartpole_dqn.py
> +def weights_init(model):
내부함수 좋습니다. 저 코멘트는 제가 긁어오느라... 없애도 될 듯요

2018-01-12 08:43 UTC, dnddnjs commented on cartpole_dqn.py
> +            return np.argmax(q_value[0])
torch.max로 한 다음에 numpy로 바꿔서 출력하면 되겠네요

2018-01-12 08:45 UTC, dnddnjs commented on cartpole_dqn.py
> +        self.fc = nn.Sequential(
Sequential로 하는게 좋을지 논의 필요할 듯

2018-01-12 08:46 UTC, keon commented on cartpole_dqn.py
> +            return np.argmax(q_value[0])
왜 넘파이로 바꿔서 출력해야하나요??

2018-01-12 08:47 UTC, dnddnjs commented on cartpole_dqn.py
> +                    torch.save(agent.model, "./save_model/cartpole_dqn.h5")
h5는 빼야할 것 같습니다

2018-01-14 09:20 UTC, dnddnjs commented on cartpole_dqn.py
> +            return np.argmax(q_value[0])
생각해보니 그럴 이유는 없겠네요. keras 썼던 코드에서 최소한으로 변형하려고 해서 그렇게 짜놨나 봅니다. 가능하면 torch tensor로 변형하면 좋겠네요

2018-01-16 02:27 UTC, merged